unis = {'Google Deepmind': 'DeepMind', 'Google Brain': 'Google', 'Cmu': 'Carnegie Mellon University',
        'Cargenie Mellon University': 'Carnegie Mellon University',
        'Carnegie Mellen University': 'Carnegie Mellon University',
        'Carnegie Mellon University': 'Carnegie Mellon University', 'Facebook Ai Research': 'Facebook',
        'University Of Virginia--> Ucla': 'University Of Virginia', 'Openai / Uc Berkeley': 'Openai',
        'Mpi For Intelligent Systems Tübingen, Germany': 'Max Planck Institute For Intelligent Systems',
        'Mit Csail': 'Mit', 'Fair': 'Facebook', 'University Of Oxford': 'Oxford', 'Harvard University': 'Harvard',
        'Uber Ai Labs': 'Uber', 'Uber Ai Labs & University Of Central Florida': 'Uber',
        'Uber Atg / University Of Toronto': 'Uber', 'Uber/Cmu': 'Uber',
        'University Of Cambridge & Uber': 'University Of Cambridge', 'Cambridge/Mpi': 'University Of Cambridge',
        'University Of Cambridge And Mpi Tübingen': 'University Of Cambridge',
        'University Of Cambridge, Alan Turing Institute': 'University Of Cambridge',
        'Columbia University In The City Of New York': 'Columbia University',
        'Columbia University Medical Center': 'Columbia University', 'Aalto University & Nvidia': 'Aalto University',
        'Alan Turing Institute & University Of Warwick': 'Alan Turing Institute', 'Amazon / Ucsb': 'Amazon',
        'Amazon Ai & Caltech': 'Amazon', 'Amazon Research': 'Amazon', 'Amazon Research Tübingen': 'Amazon',
        'Amazon.Com': 'Amazon', 'Ant Financial Services Group': 'Ant Financial',
        'Artificial Intelligence Department, Ant Financial': 'Ant Financial', 'Apple Inc.': 'Apple',
        'Cornell University': 'Cornell', 'Deepmind/University Of Alberta': 'DeepMind', 'Google Inc': 'Google',
        'Google Inc.': 'Google', 'Google Llc': 'Google', 'Google Research': 'Google', 'Google Research, Ny': 'Google',
        'Google Uk': 'Google', 'Google, Inc.': 'Google', 'Google, Usa': 'Google', 'Facebook / Nyu': 'Facebook',
        'Facebrinnook Ai Research And Tel Aviv University': 'Facebook', 'Facebook Ai Research, Nyu': 'Facebook',
        'Facebook Artificial Intelligence Research': 'Facebook', 'Facebook Research': 'Facebook',
        'Oxford And Deepmind': 'Oxford', 'Oxford, Deepmind': 'Oxford', 'Northwestern': 'Northwestern University',
        'Northwestern U': 'Northwestern University', 'Ut Austin': 'University Of Texas, Austin',
        'Ut Austin & Amazon': 'University Of Texas, Austin',
        'Ut Austin - Sentient Technologies': 'University Of Texas, Austin', 'Ut-Austin': 'University Of Texas, Austin',
        'Weizmanninstitute': 'Weizmann Institute Of Science',
        'Tu Darmstadt + Max Planck Institute For Intelligent Systems': 'Tu Darmstadt',
        'Eecs, Uc Berkeley': 'University Of California, Berkeley',
        'Eecs Department, University Of California, Berkeley': 'University Of California, Berkeley',
        'Berkeley': 'University Of California, Berkeley', 'Uc Berkeley': 'University Of California, Berkeley',
        'University Of California At Berkeley': 'University Of California, Berkeley',
        'University Of California Berkeley': 'University Of California, Berkeley', 'Google / U. Michigan': 'Google',
        'Google Ai': 'Google', 'Google Brain / Cornell University': 'Google',
        'Google Brain And Princeton University': 'Google', 'Google Brain Robotics': 'Google',
        'Google Deepmind And Inria': 'DeepMind', 'Deep Mind': 'Deepmind', 'Deepmind, University Of Oxford': 'Deepmind',
        'Yandex; Msu': 'Yandex', 'University At Albany, State University Of New York': 'University At Albany',
        'Massachusetts Institute Of Technology': 'Mit', 'Nyu': 'New York University', 'Skoltech & Criteo': 'Skoltech',
        'Zhejiang University & Tencent Ai Lab': 'Zhejiang University',
        'Mcgill University / Facebook': 'Mcgill University', 'U Oxford': 'Oxford',
        'University Of California At San Diego': 'University Of California San Diego',
        'Microsoft Research Ai': 'Microsoft', 'Microsoft Ai & Research': 'Microsoft', 'Microsoft Research': 'Microsoft',
        'Baidu Research, Usa': 'Baidu', 'Baidu Research Usa': 'Baidu', 'Baidu Research': 'Baidu',
        'Microsoft Maluuba': 'Microsoft', 'Technion – Israel Institute Of Technology': 'Technion',
        'Technion Israeli Institute Of Technology': 'Technion',
        'Okinawa Institute Of Science And Technology Graduate University': 'Okinawa Institute Of Science And Technology',
        'Nvidia Research': 'Nvidia', 'Microsoft Research Cambridge': 'Microsoft',
        'Tel Aviv University, Google': 'Tel Aviv University', 'Stanford University & Google': 'Stanford University',
        'Mit, Tau': 'Mit', 'Magic Leap, Inc': 'Magic Leap', 'Magic Leap Inc.': 'Magic Leap',
        'Magic Leap, Inc.': 'Magic Leap', 'Princeton University And Google Brain': 'Princeton University',
        'Univ Of Toronto | Toronto': 'University Of Toronto',
        'Department Of Electrical And Computer Engineering, University Of Toronto': 'University Of Toronto',
        'Hebrew University Of Jerusalem, Israel': 'Hebrew University',
        'University Of Illinois Uc': 'University Of Illinois Urbana-Champaign', 'Mcgill': 'Mcgill University',
        'Stanford University, California': 'Stanford University', 'Microsoft Research Asia': 'Microsoft',
        'The University Of Oxford': 'Oxford',
        'Princeton University And Institute For Advanced Study': 'Princeton University',
        'Princeton': 'Princeton University', 'Princeton Univerisity': 'Princeton University',
        'The University Of Texas At Austin': 'University Of Texas, Austin',
        'Epfl': 'École Polytechnique Fédérale De Lausanne',
        'École Polytechnique Fédérale D': 'École Polytechnique Fédérale De Lausanne',
        'University Of Toronto And Vector Institute': 'Univeristy Of Toronto',
        'Universita Di Pisa': 'University Of Pisa', 'Cambridge': 'University Of Cambridge',
        'Columbia': 'Columbia University', 'Department Of Statistics, Columbia University': 'Columbia University',
        'Eth Zurich And University Of Zurich': 'Eth Zurich', 'Eth Zurich - Max-Planck-Institute': 'Eth Zurich',
        'Eth Zürich': 'Eth Zurich', 'Ethz': 'Eth Zurich', 'Openai / University Of Edinburgh': 'Openai',
        'Iiis, Tsinghua University': 'Tsinghua University', 'California Institute Of Technology': 'Caltech',
        'Georgia Tech': 'Georgia Institute Of Technology',
        'Georgia Institute Of Technology / Facebook Ai Research': 'Georgia Institute Of Technology',
        'Tecent Ai Lab': 'Tencent Ai Lab', 'Tencent': 'Tencent Ai Lab', 'Yale School Of Public Health': 'Yale',
        'Yale University': 'Yale', " University Of Melbourne, Australia": 'University Of Melbourne',
        '"Department Of Bio And Brain Engineering, Kaist, Korea"': 'Kaist',
        '"University Of Adelaide, Australia"': 'University Of Adelaide',
        '"University Of California, Berkeley"': 'University Of California, Berkeley',
        '"University Of Washington, Seattle"': 'University Of Washington', 'Aamzon': 'Amazon',
        'Alibaba Group': 'Alibaba', 'Alibaba Us': 'Alibaba', 'Alibaba Youku Cognitive And Intelligent Lab': 'Alibaba',
        'Amazon Web Services': 'Amazon', 'Aws Ai Labs': 'Amazon', 'Apple & Univesity Of Washington': 'Apple',
        'Apple, Inc.': 'Apple', 'Carnegie Mellon University / Bosch Center For Ai': 'Carnegie Mellon University',
        'Carnegie Mellon University Robotics Institute': 'Carnegie Mellon University',
        'Cmu & Ttic': 'Carnegie Mellon University', 'Cmu Mld': 'Carnegie Mellon University',
        'Deepmind / Imperial College London': 'Deepmind', 'Eth': 'Eth Zurich', 'Eth Zurich': 'Eth Zurich',
        'Eth Zurich - Max Planck Institute': 'Eth Zurich', 'Facebook Ai Research / Ucl': 'Facebook',
        'Facebook Fair': 'Facebook', 'Facebook Reality Labs': 'Facebook', 'Googl': 'Google',
        'Google / University Of Alberta          ': 'Google', 'Google Ai Princeton': 'Google',
        'Google Ai Residency Program': 'Google', 'Google And Crest/Ensae': 'Google',
        'Google And Tel Aviv University': 'Google', 'Google Brain & University Of Toronto': 'Google',
        'Google Brain / University Of Colorado': 'Google', 'Google Research And Tel Aviv University': 'Google',
        'Google Research Brain Team': 'Google', 'Google Research Nyc': 'Google',
        'Google Research, Brain Team': 'Google', 'Google Zurich': 'Google', "Huawei Noah'S Ark Lab": 'Huawei',
        "Huawei Paris Research Center": 'Huawei', "Huawei Technologies": 'Huawei', 'Ibm Research': 'Ibm',
        'Ibm Research - Zurich': 'Ibm', 'Ibm Research Ai': 'Ibm', 'Ibm Research, Mit-Ibm Watson Ai Lab': 'Ibm',
        'Ibm Research, Thomas J. Watson Research Center': 'Ibm', 'Ibm T. J. Watson': 'Ibm',
        'Ibm T. J. Watson Research Center': 'Ibm', 'Ibm T.J. Watson Research Center': 'Ibm',
        'Ibm-Mit Research Lab': 'Ibm', 'Inria And Google': 'Inria', 'Inria Grenoble Rhone-Alpes': 'Inria',
        'Inria Lille - Nord Europe': 'Inria', 'Inria Paris': 'Inria', 'Inria Saclay': 'Inria', 'Inria Uca,': 'Inria',
        'Inria/Google': 'Inria', 'Kaist, Aitrics': 'Kaist', 'Kaist,Aitrics': 'Kaist', 'Micr': 'Microsoft',
        'Microsoft Inc.': 'Microsoft', 'Microsoft Research Montreal': 'Microsoft',
        'Microsoft Research Redmond': 'Microsoft', 'Microsoft Research, Cambridge': 'Microsoft', 'Mila': 'Mila',
        'Mila - Mcgill University': 'Mila', 'Mila - Quebec Ai Institute/Mcgill University': 'Mila',
        'Mila - Université De Montréal': 'Mila', 'Mila / Fair': 'Mila', 'Mila / U. Montreal': 'Mila',
        'Mila, Montreal': 'Mila', 'Mila, Udem': 'Mila', 'Mila, University Of Montreal': 'Mila',
        'Mila, Université De Montréal': 'Mila', 'Nvidia, University Of Sydney': 'Nvidia',
        'Preferred Networks Inc.': 'Preferred Networks', 'Preferred Networks, Inc.': 'Preferred Networks',
        'Cornell University / Google Brain': 'Cornell', 'Cornell University / Uber': 'Cornell',
        'Google / University Of Alberta': 'Google', 'Stanford And Databricks': 'Stanford University',
        'Stanford Universtiy': 'Stanford University', 'Stanford, Google, Uc Berkeley': 'Stanford University',
        'Technion - Israeli Institute Of Technology': 'Technion', 'Technion And Google': 'Technion',
        'Tencent; The Chinese University Of Hong Kong': 'Tencent',
        'Uc Berkeley School Of Public Health': 'University Of California, Berkeley', 'Www.Amazon.Com': 'Amazon',
        'Broad Institute Of Mit And Harvard': 'Broad Institute', 'Mit-Ibm Watson Ai Lab': 'Mit',
        'Mit-Ibm Watson Ai Lab / Ibm Research': 'Mit', 'Mit-Ibm Watson Ai Lab, Ibm Research': 'Mit',
        'Mit-Ibm, University Of Edinburgh': 'Mit',
        'Georgia Institute Of Technolodgy': 'Georgia Institute Of Technology',
        'Georgia Institute Of Technology, Usa': 'Georgia Institute Of Technology',
        'Georgia Institution Of Technology': 'Georgia Institute Of Technology',
        'Georgia Tech & Facebook Ai Research': 'Georgia Institute Of Technology', 'Oxford Robotics Insitute': 'Oxford',
        'Oxford University': 'Oxford', 'Univeristy Of Oxford': 'Oxford', 'Unversity Of Oxford': 'Oxford',
        'Tripods Center Of Data Science - Cornell University': 'Cornell', 'Tsinghua Univerisity': 'Tsinghua University',
        'Tsinghua University, China': 'Tsinghua University', 'Cnrs Université Paris-Sud, Inria Paris, Edf R&D': 'Inria',
        'Korea Advanced Institute Of Science And Technology': 'Kaist',
        'Ecole Polytechnique Federale De Lausanne': 'École Polytechnique Fédérale De Lausanne',
        'Ecole Polytechnique Fédérale De Lausanne': 'École Polytechnique Fédérale De Lausanne',
        'Cambridge University': 'University Of Cambridge',
        'University Of Cambridge / Columbia University': 'University Of Cambridge', 'Duke': 'Duke University',
        'Duke U': 'Duke University', 'Harvard University, Usa': 'Harvard',
        'Ucla Math': 'University Of California, Los Angeles', 'Ucla': 'University Of California, Los Angeles',
        'Aarhus University, Madalgo': 'Aarhus University', 'Adobe Research / U. Michigan': 'Adobe',
        'Adobe Research': 'Adobe', 'Amazon + University Of Washington': 'Amazon', 'Amazon Ai': 'Amazon',
        'Amazon Aws': 'Amazon', 'Amazon Research Cambridge': 'Amazon', 'Apple & University Of Washington': 'Apple',
        'Arm Research': 'Arm', 'Baidu Inc.': 'Baidu', 'Baidu Usa': 'Baidu',
        'Bar-Ilan University': 'Bar Ilan University', 'Ben-Gurion University': 'Ben Gurion University',
        'Ben-Gurion University Of The Negev': 'Ben Gurion University', 'Cornell / Uber': 'Cornell',
        'Cornell Tech, Cornell University': 'Cornell', 'Cornell Univeristy': 'Cornell',
        'Cornell University And Google Brain': 'Cornell', 'Cornell University Ohio State University': 'Cornell',
        'Deepmind & University Of Oxford': 'Deepmind', 'Deepmind Montreal': 'Deepmind',
        'Deepmind Paris And Inria Lille - Nord Europe': 'Deepmind', 'Deepmind Technologies': 'Deepmind',
        'Deepmind, Ucl': 'Deepmind', 'Ecole Normale Superieure, Paris': 'Ecole Normale Supérieure',
        'Eth Zürich - Mpi Tübingen': 'Eth Zurich', 'Facebook - Fair': 'Facebook', 'Facebook Ai': 'Facebook',
        'Facebook Ai Research And University Of Oxford': 'Facebook', 'Facebook Ai Research Paris': 'Facebook',
        'Facebook Ai Research/Cmu': 'Facebook', 'Georgia Institute Of Technolog': 'Georgia Institute Of Technology',
        'Georgia Inst. Of Technology': 'Georgia Institute Of Technology', 'Google & University Of Toronto': 'Google',
        'Google Ai Resident': 'Google', 'Google Canada': 'Google',
        'Google Research And The Hebrew University Of Jerusalem, Israel': 'Google',
        'Hebrew University Jerusalem Israel': 'Hebrew University',
        'Hebrew University Of Jerusalem': 'Hebrew University', 'Ibm Almaden Research Center': 'Ibm',
        'Ibm India Research Lab': 'Ibm', 'Ibm Research - China': 'Ibm', 'Ibm Research - India': 'Ibm',
        'Ibm Research -- Zurich': 'Ibm', 'Ibm Research Gmbh': 'Ibm', 'Ibm Research, Ny': 'Ibm',
        'Ibm T. J. Watson Research': 'Ibm', 'Ibm T.J Watson Research Center': 'Ibm',
        'Ibm T.J.Watson Research Center': 'Ibm', 'Ibm Thomas J. Watson Research Center': 'Ibm',
        'Inria & Ecole Polytechnique': 'Inria', 'Inria & University College London': 'Inria',
        'Inria - Ecole Normale Superieure': 'Inria', 'Inria - Paris': 'Inria', 'Inria / Google': 'Inria',
        'Inria Grenoble': 'Inria', 'Inria Lille': 'Inria', 'Inria Lille - Sequel Team': 'Inria',
        'Inria Sophia-Antipolis': 'Inria', 'Inria, Ecole Normale Superieure': 'Inria',
        'Inria, Université Paris-Saclay': 'Inria', 'Intel - Artificial Intelligence Products Group': 'Intel',
        'Intel Ai Lab': 'Intel', 'Intel Ai Labs': 'Intel', 'Intel Ai Products Group': 'Intel', 'Intel Corp.': 'Intel',
        'Intel Corporation': 'Intel', 'Intel Labs': 'Intel', 'Intel Labs And Mit': 'Intel', 'Intel Labs China': 'Intel',
        'Intel Nervana': 'Intel', 'Megvii Inc': 'Megvii', 'Megvii, Face++': 'Megvii', 'Megvii（Face++': 'Megvii',
        'Microsoft Research & University Of Maryland': 'Microsoft', 'Microsoft Research India': 'Microsoft',
        'Microsoft Research New York': 'Microsoft', 'Microsoft Research, Redmond, Wa': 'Microsoft',
        'Mila & Idiap & Epfl': 'Mila', 'Mila & University Of Montreal': 'Mila', 'Mila / Kakao Brain': 'Mila',
        'Mila / U.Montreal': 'Mila', 'Mila, Mcgill University': 'Mila',
        'Mila, Polytechnique Montréal, Element Ai': 'Mila', 'Mila, University Of Montreal, Msr Montreal': 'Mila',
        'Mit Media Lab': 'Mit', 'Mit-Ibm Watson Ai Lab, Ibm Research Ai': 'Mit', 'Mit/Google': 'Mit',
        'Mit–Ibm Watson Ai Lab': 'Mit', 'Msu': 'Moscow State University', 'Nvidia & Aalto University': 'Nvidia',
        'Nvidia / Caltech': 'Nvidia', 'Nvidia Corporation': 'Nvidia', 'Nvidia Research; Aalto University': 'Nvidia',
        'Nvidia; Aalto University': 'Nvidia', 'Qualcomm Ai Research': 'Qualcomm',
        'Samsung Ai Center Cambridge': 'Samsung', 'Samsung Ai Center, Moscow': 'Samsung',
        'Samsung Ai Centre': 'Samsung', 'Samsung Research America': 'Samsung', 'Stanford': 'Stanford University',
        'Stanford University / Afresh': 'Stanford University',
        'Stanford University And Pinterest': 'Stanford University',
        'Stanford Vision & Learning Lab': 'Stanford University', 'Stanford.Edu': 'Stanford University',
        'Tau, Google': 'Tel Aviv University', 'Tel Aviv University / Google': 'Tel Aviv University',
        'Tel-Aviv University': 'Tel Aviv University', 'Uc Berkeley Covariant': 'University Of California, Berkeley',
        'Univ Of Oxford': 'Oxford', 'Weizmann Inst.': 'Weizmann Institute Of Science',
        'Weizmann Institute': 'Weizmann Institute Of Science',
        'Weizmann Institute, Israel': 'Weizmann Institute Of Science',
        'Weizmann Istitute Of Science': 'Weizmann Institute Of Science',
        'Yandex; National Research University Higher School Of Economics': 'Yandex',
        'Yandex; University Of Amsterdam': 'Yandex', 'Technion And Google Inc.': 'Technion',
        'Carnegie Mellon University, Language Technologies Institute': 'Carnegie Mellon University',
        'Megvii（Face++）': 'Megvii', 'University Of Californian, Berkeley': 'University Of California, Berkeley',
        'Ieor Department, Columbia University': 'Columbia University',
        '" University Of Oregon, Usa"': 'University Of Oregon',
        '"Chinese Academy Of Sciences, China"': "Chinese Academy Of Sciences",
        '"Data Analytics And Intelligence Lab, Alibaba Group"': "Alibaba", '"Ibm Research, India"': "Ibm",
        '"South China University Of Technology, China"': "South China University Of Technology",
        '"University Of Salzburg, Austria"': "University Of Salzburg", '4Paradigm Inc.': '4Paradigm',
        'Ai Lab, Samsung Research China - Beijing': 'Samsung', 'Ai Research Of Jd.Com': 'Jd.Com',
        'Alibaba Inc.': 'Alibaba', 'Amazon Research Berlin': 'Amazon', 'A2I2': 'Allen Institute For Ai',
        'Allen Institute For Artificial Intelligence': 'Allen Institute For Ai', 'Allenai': 'Allen Institute For Ai',
        'Apple Inc': 'Apple',
        'Bosch Center For Artificial Intelligence Bcai': 'Bosch Center For Artificial Intelligence',
        'Brown': 'Brown University', 'Bytedance Ai Lab': 'Bytedance',
        'Centrum Wiskunde & Informatica, Amsterdam': 'Centrum Wiskunde & Informatica',
        'Cnrs & Sorbonne Université': 'Cnrs', 'Cnrs And Ens': 'Cnrs', 'Cnrs And Univ. Lille': 'Cnrs',
        'Cnrs, Irit': 'Cnrs', 'Cnrs/Lip6': 'Cnrs', 'College Of William & Mary': 'College Of William And Mary',
        'Cornell/Google': 'Cornell', 'Criteo Ai Lab': 'Criteo', 'D-Wave Systems Inc.': 'D-Wave',
        'Dalhousie University/Vector Institute': 'Dalhousie University', 'Creatis Umr Cnrs 5220': 'Creatis',
        'Crest, Ensae': 'Crest', 'Dauphine University - Cea List': 'Dauphine University',
        'Deepmind Technologies Ltd': 'Deepmind', 'Department Of Automation, Tsinghua University': 'Tsinghua University',
        'Department Of Computer Science, University Of North Carolina At Chapel Hill': 'University Of North Carolina At Chapel Hill',
        'Duke Univsersity': 'Duke University',
        'Eberhard Karls Universität Tübingen': 'Eberhard Karls University Of Tübingen', 'Ensae Paris': 'Ensae',
        'Facebook Ai Reseach': 'Facebook', 'Facebook Ai Research And Tel Aviv University': 'Facebook',
        'Facebook Ai Research Paris & Inria Lille': 'Facebook', 'Facebook, Inc.': 'Facebook',
        'Facebook, Ucl': 'Facebook', 'Facebook/Ens/Inria': 'Facebook',
        'Fujitsu R&D Center Co., Ltd. Shanghai Laboratory': 'Fujitsu', 'Fujitsu Laboratories Ltd.': 'Fujitsu',
        'Gatech Tech': 'Gatech', 'Gatsby Computational Neuroscience Unit': 'University College London',
        'Gatsby Unit, Ucl': 'University College London',
        'Gatsby Unit, University College London': 'University College London',
        'Gatsby Unit，Ucl': 'University College London',
        'Georgia Institute Of Technoloy': 'Georgia Institute Of Technology',
        'Georgia Tech / Msr Redmond': 'Georgia Institute Of Technology',
        'German Research Center For Aritificial Intelligence': 'German Research Center For Artificial Intelligence',
        'Google Ai, Zurich': 'Google', 'Google Brain, Google Inc.': 'Google', 'Google Israel': 'Google',
        'Google Research / University Of Colorado': 'Google',
        'Google Research And Courant Institute Of Mathematical Sciences': 'Google', 'Harvard Medical School': 'Harvard',
        'Health Policy And Management, Yale School Of Public Health': 'Yale',
        'Hebrew University, Jerusalem': 'Hebrew University',
        'Higher School Of Economics': 'Higher School Of Economics, Samsung Ai Center Moscow',
        'Hongkong University Of Science And Technology': 'Hong Kong University Of Science And Technology',
        'Huawei Noah’S Ark Lab': 'Huawei', 'Huawei Technologies Canada': 'Huawei', 'Ias, Princeton': 'Ias',
        'Ias/Princeton': 'Ias', 'Ibm Research, T. J. Watson Research Center': 'Ibm', 'Ibm Research- India': 'Ibm',
        'Ibm, Almaden': 'Ibm', 'Idiap & Epfl': 'Idiap Research Institute', 'Iflytek Research': 'Iflytek',
        'Imagia, Dalhousie University': 'Imagia', 'Inria - Ecole Normale Supérieure': 'Inria', 'Inria - Ens': 'Inria',
        'Inria - Loria': 'Inria', 'Inria Saclay Ile-De-France': 'Inria', 'Inria Sequel': 'Inria',
        'Inria, École Normale Supérieure': 'Inria', 'Institute Of Computing Technology': 'Chinese Academy Of Sciences',
        'Institute Of Computing Technology, Cas': 'Chinese Academy Of Sciences',
        'Institute Of Computing Technology, Cas, China': 'Chinese Academy Of Sciences',
        'Institute Of Computing Technology, Chinese Academy Of Sciences': 'Chinese Academy Of Sciences',
        'Institute Of Information Engineering, Cas': 'Chinese Academy Of Sciences',
        'Institute Of Information Engineering, Cas, China': 'Chinese Academy Of Sciences',
        'Institute Of Information Engineering,Chinese Academy Of Sciences': 'Chinese Academy Of Sciences',
        'Instituto De Telecomunicações': 'Instituto De Telecomunicacoes', 'Intel Ai': 'Intel',
        'Johns Hopkins University + Microsoft Semantic Machines': 'Johns Hopkins University',
        'Karolinska Institutet': 'Karolinska Institute', 'Kth Royal Institute Of Technology': 'Kth',
        'Kth, Royal Institute Of Technology': 'Kth', 'Layer6 Ai': 'Layer 6 Ai', 'Linkedin Corporation': 'Linkedin',
        'Lip6, Sorbonne Universite': 'Sorbonne', 'Lip6 - Sorbonne Universités': 'Sorbonne',
        'Max Planck Institute For Informatics': 'Max Planck Institute',
        'Max Planck Institute For Intelligent Systems': 'Max Planck Institute',
        'Max-Planck Institute For Intelligent Systems': 'Max Planck Institute',
        'Max Planck Institute For Software Systems': 'Max Planck Institute',
        'Mcgill University / Deepmind': 'Mcgill University', 'Mcgill University / Mila': 'Mcgill University',
        'Mcgill University And Mila': 'Mcgill University', 'Mcgill University, Mila Montreal': 'Mcgill University',
        'Mcgill University/Fair': 'Mcgill University',
        'Mcgill University; Mila; Facebook Ai Research': 'Mcgill University', 'Mcgill/Mila': 'Mcgill University',
        'Microsoft Research New England': 'Microsoft', 'Microsoft Research, Redmond': 'Microsoft',
        'Microsoft.Com': 'Microsoft', 'Mila / University Of Montreal': 'Mila', 'Mila / Université De Montréal': 'Mila',
        'Mila-Udem': 'Mila', 'Mila/Udem': 'Mila', 'Mila;Imagia': 'Mila', 'Mlcb, D-Bsse, Eth Zurich': 'Eth Zurich',
        'Mitsubishi Electric Corporation': 'Mitsubishi Electric',
        'Mitsubishi Electric Research Labs': 'Mitsubishi Electric', 'Nec Corporation': 'Nec',
        'Nec Laboratories America': 'Nec', 'Nec Laboratories America, Inc.': 'Nec', 'Nec Labs': 'Nec',
        'Nec Labs America': 'Nec', "Noah'S Ark Lab": 'Huawei', "Noah'S Ark Laboratory, Huawei": 'Huawei',
        "Noah’S Ark Lab, Huawei Technologies": 'Huawei', 'Nvidia / Bar-Ilan University': 'Nvidia', 'Open Ai': 'Openai',
        'Qualcomm Research': 'Qualcomm', 'Riken / The University Of Tokyo': 'Riken', 'Riken Aip': 'Riken',
        'Riken Center For Advanced Intelligence Project': 'Riken', 'Ruhr-University Bochum': 'Ruhr University Bochum',
        'Ruhr-Universität Bochum': 'Ruhr University Bochum', 'Rutgers Univerity': 'Rutgers University',
        'Rutgers': 'Rutgers University', 'Rutgers University, New Jersey': 'Rutgers University',
        'Rutgers University-Newark': 'Rutgers University', 'Samsung Advanced Institute Of Technology': 'Samsung',
        'Samsung Ai': 'Samsung', 'Samsung Ai Centre Cambridge/ Imperial College London': 'Samsung',
        'Samsung Artificial Intelligence Center': 'Samsung', 'Samsung Electronics': 'Samsung',
        'Samsung Research China - Beijing': 'Samsung', 'Stanford U.': 'Stanford University',
        'Stanford, Uc Berkeley': 'Stanford University', 'Technion - Israel Institute Of Technology': 'Technion',
        'Technion, Google': 'Technion', 'Technion, I.I.T': 'Technion',
        'Technion- Israel Institute Of Technology': 'Technion', 'Technion--Israel Institute Of Technology': 'Technion',
        'Tel-Aviv University & Facebook Ai Research': 'Tel Aviv University',
        'The Chinese University Of Hongkong': 'The Chinese University Of Hong Kong',
        'U.C. Berkeley': 'University Of California, Berkeley', 'Uber Ai And University Of Central Florida': 'Uber',
        'Uber Ai': 'Uber', 'Uc Berkeley & Covariant': 'University Of California, Berkeley',
        'Uc Berkeley/Carnegie Mellon University': 'University Of California, Berkeley',
        'Weizmann Institute Of Science, Israel': 'Weizmann Institute Of Science', 'Yale School Of Medicine': 'Yale',
        'Yale Univ': 'Yale', 'Yandex Research, Msu Im. Lomonosova': 'Yandex',
        'National University Of Singapore,': 'National University Of Singapore',
        'New York Univeristy': 'New York University', 'Texas A&M': 'Texas A&M University',
        'The Hebrew University Of Jerusalem': 'Hebrew University', 'The University Of Tokyo': 'University Of Tokyo',
        'The University Of Tokyo / Riken': 'University Of Tokyo',
        'The University Of Tokyo /Riken': 'University Of Tokyo', 'Uber Atg': 'Uber', 'Uber Labs': 'Uber',
        'University Of California Los Angeles': 'University Of California, Los Angeles',
        'Mathematical Institute Oxford': 'Oxford', 'Oxford University Hospitals Nhs Foundation Trust': 'Oxford',
        'University Of Oxford, Deepmind': 'Oxford', 'Tsinghua': 'Tsinghua University',
        'University Of Texas At Austin': 'University Of Texas, Austin',
        'Ut-Austin & University Of Washington': 'University Of Texas, Austin',
        'U Of Pennsylvania': 'University Of Pennsylvania',
        'University Of Pennsylvania / Uc Berkeley': 'University Of Pennsylvania',
        'University Of Washington, Allen Institue For Ai': 'University Of Washington',
        'Univeristy Of Toronto': 'University Of Toronto',
        'University Of Toronto, Vector Institute': 'University Of Toronto',
        'University Of Toronto, Vector Institute, Nvidia': 'University Of Toronto',
        'Vector Institute And University Of Toronto': 'Vector Institute', 'Peking Unversity': 'Peking University',
        'Mila / École Polytechnique De Montréal': 'Mila', 'Mila; Imagia': 'Mila',
        'University Of Tokyo / Riken': 'University Of Tokyo',
        'University Of Cambridge, The Alan Turing Institute, Ucla': 'University Of Cambridge',
        'University Of Cambridge/Deepmind': 'University Of Cambridge', 'Huawei Technology R&D Uk': 'Huawei',
        'Cmu / Google Brain / Stanford': 'Carnegie Mellon University',
        'Cmu, Google Brain': 'Carnegie Mellon University',
        'Cmu, Strategic Machine, Strategy Robot, Optimized Markets': 'Carnegie Mellon University',
        'Cmu, Usa': 'Carnegie Mellon University', 'Cornell Tech': 'Cornell',
        'Cornell University & Asapp Research': 'Cornell', 'Cornell University / Asapp Research': 'Cornell',
        'Cornell University And Google Ai': 'Cornell', 'Google - Deepmind': 'Deepmind', 'Google / Uc Merced': 'Google',
        'Google And Mit': 'Google', 'Google Brain & Crest - Ensae': 'Google', 'Google Brain / Stanford': 'Google',
        'Google Brain Amsterdam': 'Google', 'Google Brain Robotics & Columbia University': 'Google',
        'Google Health': 'Google', 'Google Research / Harvard': 'Google', 'Google Research, Brain': 'Google',
        'Google Switzerland Gmbh': 'Google', 'Google, Brain Team, Zurich': 'Google', 'Google, Uc Berkeley': 'Google',
        'Google/Cmu': 'Google', 'Harvard School Of Public Health': 'Harvard', 'Harvard University/Google': 'Harvard',
        'Hebrew University And Google Research': 'Hebrew University',
        'Princeton University, Google Ai Princeton': 'Princeton University',
        'Princeton University X, Alphabet Inc.': 'Princeton University',
        'Princeton Neuroscience Institute': 'Princeton University', 'Rutgers University - Newark': 'Rutgers University',
        'Rutgers University/Google': 'Rutgers University', 'Salesforce Research': 'Salesforce',
        'Samsung Ai Center': 'Samsung', 'Samsung Ai Center Cambridge & University Of Oxford': 'Samsung',
        'Samsung Ai Centre Cambridge': 'Samsung',
        'Samsung Electronics, Samsung Advanced Institute Of Technology': 'Samsung', 'Samsung Research': 'Samsung',
        'Samsung Sds': 'Samsung', 'Samsung, Stanford, Hkust': 'Samsung', 'Samsung-Hse Laboratory': 'Samsung',
        'Samsung-Hse Laboratory, National Research University Higher School Of Economics': 'Samsung',
        'Standord': 'Stanford University', 'Stanford University - Purdue University': 'Stanford University',
        'Stanford University / Google Research': 'Stanford University',
        'Tel Aviv University And Google': 'Tel Aviv University',
        'University Of Alberta / Google Brain': 'University Of Alberta',
        'University Of Alberta / Deepmind': 'University Of Alberta', 'Tsinghua Univeristy': 'Tsinghua University',
        'Tsinghua Univ.': 'Tsinghua University', 'Tsinghua Univiersity': 'Tsinghua University',
        'Tsinghua-Berkeley Shenzhen Institute': 'Tsinghua University',
        'Tsinghua-Berkeley Shenzhen Institute, Tsinghua University': 'Tsinghua University',
        'Uber Ai / University Of Sydney': 'Uber', 'Uber Ai; Recursion': 'Uber',
        'Department Of Management Science And Engineering, Stanford University': 'Stanford University',
        'Kaust And Stanford University': 'Kaust', 'Ntt Communication Science Laboratories': 'Ntt',
        'Ntt Communication Science Labs.': 'Ntt', 'Ntt Research, Phi Lab / Stanford University': 'Ntt',
        'Ntt Software Innovation Center': 'Ntt', 'Nvidia, Biu': 'Nvidia',
        'University Of Genova- Mit - Iit': 'University Of Genova', 'Mit Csail / Nvidia': 'Mit',
        'Mit Lincoln Laboratory': 'Mit', 'Mobileye & Huji': 'Mobileye',
        'Massachusetts Institute Of Technology Mit': 'Mit', 'Massachussets Institute Of Technology': 'Mit',
        'Boston University & Mit-Ibm Watson Ai Lab, Ibm Research': 'Boston University',
        'Boston University And Amazon': 'Boston University', 'Boston University, Google Ai': 'Boston University',
        'University Of Massachusetts': 'University Of Massachusetts, Amherst', 'Microsoft Cloud Ai': 'Microsoft',
        'Microsoft Corporation': 'Microsoft', 'Microsoft Dynamics 365 Ai': 'Microsoft',
        'Microsoft Research / Ucl': 'Microsoft', 'Microsoft Research Asia, Beijing, China': 'Microsoft',
        'Microsoft Research Nyc': 'Microsoft', 'Microsoft Research, Cambridge, Uk': 'Microsoft',
        'Johns Hopkins + Microsoft': 'Johns Hopkins University',
        'Johns Hopkins University, Usa': 'Johns Hopkins University', 'Jpmorgan': 'Jp Morgan',
        'Jpmorgan - Ai Research': 'Jp Morgan', 'Kaist-Viclab': 'Kaist',
        'Uc Berkeley & Covariant.Ai': 'University Of California, Berkeley', 'Carnegie': 'Carnegie Mellon University',
        'Carnegie Mellon Univerisity': 'Carnegie Mellon University',
        'Carnegie Mellon University, Petuum Inc.': 'Carnegie Mellon University',
        'Petuum Inc. / Carnegie Mellon University': 'Petuum Inc.',
        'Petuum, Inc. And Imperial College London': 'Petuum Inc.', 'Adobe, Cmu': 'Adobe', 'Adobe Research, Us': 'Adobe',
        'Department Of Computer Science And Technology, Tsinghua University': 'Tsinghua University',
        'Institute For Network Sciences And Cyberspace, Tsinghua University': 'Tsinghua University',
        'University Of Oxford & The Alan Turing Institute': 'Oxford',
        'University Of Oxford / Facebook Ai Research': 'Oxford', 'Oxford Robotics Institute': 'Oxford',
        'Institut Polytechnique De Paris/ University Of Oxford': 'Oxford',
        'Fmrib Centre - University Of Oxford': 'Oxford',
        'Georgia Tech / Facebook Ai Research': 'Georgia Institute Of Technology',
        'University College London Facebook Ai Research': 'University College London',
        'University College London; Emotech Labs': 'University College London', 'DeepMind': 'DeepMind',
        'School Of Computer Science, Georgia Tech': 'Yale',
        'Georgia Institute Of Technology And Emory University': 'Yale', 'Georgia Institute Of Techology': 'Yale',
        'Mcgill University / Mila / Deepmind Montreal': 'Mcgill University',
        'Mcgill University / Mila / Fair': 'Mcgill University', 'Mcgill University / Openai': 'Mcgill University',
        'Mcgill / Mila': 'Mcgill University', 'Deepmind & Ucl': 'Deepmind',
        'Deepmind / University Of Alberta': 'Deepmind', 'Deepmind, Mountain View': 'Deepmind',
        'University Of Illinois At Urbana Champaign': 'University of Illinois Urbana-Champaign',
        'University Of Illinois At Urbana-Champaign': 'University of Illinois Urbana-Champaign',
        'University Of Illinois Urbana Champaign': 'University of Illinois Urbana-Champaign',
        'University Of Illinois, Urbana-Champaign': 'University of Illinois Urbana-Champaign',
        'University Of Illionis At Chicago': 'University Of Illinois At Chicago',
        'University Of Illinois, Chicago': 'University Of Illinois At Chicago',
        'New York University School Of Medicine': 'New York University', 'Nyu/Berkeley': 'New York University',
        'Epfl, Switzerland': 'École Polytechnique Fédérale De Lausanne', 'Eth / University Of Zurich': 'Eth Zurich',
        'Eth Zurich, Switzerland': 'Eth Zurich',
        'Eth Zürich | University Of Zürich | Institute Of Neuroinformatics': 'Eth Zurich',
        'Computer Vision Lab, Eth Zurich': 'Eth Zurich', 'Ibm Almaden': 'Ibm', 'Ibm Corp': 'Ibm',
        'Ibm Research Ai - India': 'Ibm', 'Ibm Research Ai, India': 'Ibm', 'Ibm Research Zurich': 'Ibm',
        'Ibm Research Zürich': 'Ibm', 'Ibm Singapore': 'Ibm', 'Ibm Tj Watson Research Center': 'Ibm',
        'Megvii Technology': 'Megvii',
        " King Abdullah University Of Science And Technology, Saudi Arabia": 'King Abdullah University Of Science And Technology',
        "King Abdullah University Of Science And Techonology": 'King Abdullah University Of Science And Technology',
        'Aalto University And University Of Manchester': 'Aalto University',
        "Institute Of Neurology - Sobell Dept., University College Of London": 'University College Of London',
        'Agh University Of Science And Technology, Krakow, Poland': 'Agh University Of Science And Technology',
        'Alibaba Corp': 'Alibaba', 'Alibaba Damo Academy': 'Alibaba', 'Alibaba Group Inc.': 'Alibaba',
        'Alibaba Group U.S. Inc.': 'Alibaba', 'Alibaba Turing Lab, Alibaba Group': 'Alibaba',
        'Alibaba Us, Damo Academy': 'Alibaba', 'Allen Institute For Ai, Bar Ilan University': 'Allen Institute For Ai',
        'Allen Institute For Ai, Tel Aviv University': 'Allen Institute For Ai',
        'Allen Institute Of Artificial Intelligence': 'Allen Institute For Ai', 'Amazon - We Are Hiring!': 'Amazon',
        'Amazon Artificial Intelligence': 'Amazon', 'Beijing Insitute Of Technology': 'Beijing Institute Of Technology',
        'Berkeley Artificial Intelligence Research Lab': 'University Of California, Berkeley',
        'Bmwgroup, Unterschleissheim': 'Bmw', 'Bytedance.Inc': 'Bytedance',
        'University Of Sydney, Nvidia': 'University Of Sydney',
        'University Of Toronto & Vector Institute': 'University Of Toronto',
        'University Of Toronto / Uber Atg': 'University Of Toronto',
        'University Of Toronto / Vector Institute': 'University Of Toronto',
        'University Of Toronto Vector Institute': 'University Of Toronto',
        'University Of Toronto, Nvidia': 'University Of Toronto',
        'Qualcomm Ai Research, University Of Amsterdam': 'Qualcomm', 'Qualcomm Cr&D': 'Qualcomm',
        'Riken / University Of Tokyo': 'Riken', 'Riken, Tokyo': 'Riken', 'Sensetime Group Limited': 'Sensetime',
        'Sensetime International Pte Ltd': 'Sensetime', 'Sensetime International Pte. Ltd.': 'Sensetime',
        'Sensetime Research': 'Sensetime', 'Tencent Ai Lab': 'Tencent', 'Tencent Keen Lab': 'Tencent',
        'Tencent Keen Lab, Technical University Of Munich': 'Tencent', 'Tencent Medical Ai Lab': 'Tencent',
        'Tencent Technology': 'Tencent', 'Tencent Youtu Lab': 'Tencent', 'Waymo Llc': 'Waymo',
        'Facebook And U. Montreal': 'Facebook', 'Facebook Inc': 'Facebook', 'Hugging Face 🤗': 'Hugging Face',
        'Imperial College London / Twitter': 'Imperial College London', 'Imperial College': 'Imperial College London',
        'Ens / Fair': 'Ens Paris', 'Ens Paris & Sorbonnes Université': 'Ens Paris', 'Ens Paris Saclay': 'Ens Paris',
        'Ens Paris-Saclay': 'Ens Paris', 'Ens Paris-Saclay, Université Paris-Saclay': 'Ens Paris',
        'Ens Paris-Saclay; Ist Austria; Lpens': 'Ens Paris', 'Ecole Normale Superieure': 'Ens Paris',
        'Ecole Normale Supérieure': 'Ens Paris', 'Ecole Normale Supérieure & Lighton': 'Ens Paris', 'Ens': 'Ens Paris',
        'Inria / Ensae': 'Inria', 'Inria / Fair': 'Inria', 'Inria/U. Paris-Sud': 'Inria',
        'Kyoto University / Riken Aip': 'Kyoto University', 'Kyoto University/Riken Aip': 'Kyoto University',
        'Kyoto University/Riken Center For Aip': 'Kyoto University', 'Mila / Elementai': 'Mila', 'Mila/Mcgill': 'Mila',
        'Mipt': 'Moscow Institute Of Physics And Technology',
        'Mipt & Hse': 'Moscow Institute Of Physics And Technology', "Noah'S Ark Lab, Huawei Inc.": 'Huawei',
        "Noah'S Ark Lab, Huawei Tech Investment Co Ltd": 'Huawei', "Noah'S Ark Lab, Huawei Technologies": "Huawei",
        'Nnaisense Sa': 'Nnaisense', 'The University Of Tokyo/Riken-Aip': 'University Of Tokyo',
        'The University Of Tokyo, Preferred Networks Inc.': 'University Of Tokyo',
        'University Of Amsterdam / Qualcomm Ai Research': 'University Of Amsterdam',
        'University Of California At Berkley': 'University Of California, Berkeley',
        'Weizmann': 'Weizmann Institute Of Science', }
